version : '1.0.0'
services:
  cheese-blast-nacos:
    container_name: cheese-blast-nacos
    image: nacos/nacos-server
    build:
      context: ./nacos
    environment:
      - MODE=standalone
    volumes:
      - ./nacos/logs/:/home/nacos/logs
      - ./nacos/conf/application.properties:/home/nacos/conf/application.properties
    ports:
      - "8848:8848"
      - "9848:9848"
      - "9849:9849"
    depends_on:
      - cheese-blast-mysql
  cheese-blast-mysql:
    container_name: cheese-blast-mysql
    image: mysql:8.0.20
    build:
      context: ./mysql
    ports:
      - "3306:3306"
    volumes:
      - ./mysql/conf:/etc/mysql/conf.d
      - ./mysql/logs:/logs
      - ./mysql/data:/var/lib/mysql
    command: [
          'mysqld',
          '--innodb-buffer-pool-size=80M',
          '--default-time-zone=+8:00',
          '--lower-case-table-names=1'
        ]
    environment:
      MYSQL_DATABASE: 'cheese-blast'
      MYSQL_ROOT_PASSWORD: qwer1234
  cheese-blast-redis:
    container_name: cheese-blast-redis
    image: redis
    build:
      context: ./redis
    ports:
      - "6379:6379"
    volumes:
      - ./redis/conf/redis.conf:/home/cheese-blast/redis/redis.conf
      - ./redis/data:/data
    command: redis-server /home/cheese-blast/redis/redis.conf
  cheese-blast-nginx:
    container_name: cheese-blast-nginx
    image: nginx
    build:
      context: ./nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/html/dist:/home/cheese-blast/projects/cheese-blast-web
      - ./nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
    depends_on:
      - cheese-blast-gateway
    links:
      - cheese-blast-gateway
  cheese-blast-gateway:
    container_name: cheese-blast-gateway
    build:
      context: ./cheese-blast/gateway
      dockerfile: dockerfile
    ports:
      - "9090:9090"
  cheese-blast-service-video:
    container_name: cheese-blast-service-video
    build:
      context: ./cheese-blast/service/video
      dockerfile: dockerfile
    ports:
      - "9301:9301"
