server:
  port: 10001

spring:
  application:
    name: niuyin-tools-es
  datasource:
    url: jdbc:mysql://43.240.221.8:3306/cheese-blast?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=true&serverTimezone=GMT%2B8
    username: roydon
    password: roydon#Mysql
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: 43.240.221.8
    port: 6379
    password: roydon#Redis
    database: 1
  data:
    mongodb:
      host: 43.240.221.8
      port: 27017
      username: cheeseblast
      database: cheeseblast
      password: n3f55MhYix6CPjKw

# mybatis配置
mybatis-plus:
  type-aliases-package: com.niuyin.**.domain
  mapper-locations: classpath*:mapper/**/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

elasticsearch:
  host: 43.240.221.8
  port: 9200

logging:
  level:
    com.niuyin: debug
    org.springframework: warn
